config/routes.rb
Rails.application.routes.draw do
  get 'meetings/new'

  get 'meetings/show'

  resources :groups, shallow: true do
    resources :meetings
  end

  root "groups#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :meetings
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @meeting = Meeting.create
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/groups/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>

app/views/groups/new.html.erb
<section class="new-group">
  <h1>Nieuwe groep</h1>

  <%= form_for @group do |f| %>
  <div>
    <%= f.text_field :name %>
    <%= f.submit %>
  </div>
  <% end %>

</section>

app/views/groups/show.html.erb
<%= content_tag_for(:article, @group) do %>
  <h1><%= @group.name %></h1>

  <h2>Vergaderingen</h2>

  <p><%= link_to "Maak een agenda", new_group_meeting_path(@group) %></p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeAgenda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<%= yield %>

</div>

</body>
</html>

app/views/meetings/new.html.erb
<%= content_tag_for(:article, @meeting) do %>
<h1>Nieuwe vergadering</h1>

<%= form_for @meeting, remote: true do |f| %>
<p>
  <%= f.label :scheduled_at %>
  <%= f.datetime_field :scheduled_at %>
  <%= f.submit "Datum opslaan" %>
</p>
<% end %>

<section class="agenda">
  <h2>Agenda</h2>
</section>

<% end %>

app/views/meetings/show.html.erb
<h1>Meetings#show</h1>
<p>Find me in app/views/meetings/show.html.erb</p>